apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-rjep
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-eqsp-tenant/rhtap-demo-app/hacbs-test-project-rjep@sha256:7cc78be970e1ea2ada0002e81cb475012af7cd395ab3ffe1cab6174430c0f7d7
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
